### ISSUE TITLE
can you help about the store*?

### ISSUE THREAD

**Issue by IGNRexI** [LoveBeforT/WarcraftHelper#6]
@LoveBeforT can you fix the multi option feature for the store? please
x1 / x2 / x3 / x4 / x5
right now when I try 3, the problem occurs and it is wrong

```css
func InitShopReply() {
	buf := make([]byte, 3)
	offset, optIdx := 0, 0
	WriteUint8(&buf, outshoplist, &offset)
	WriteUint16(&buf, uint16(len(ShopItemList)), &offset)
	for _, item := range ShopItemList {
		tmp := make([]byte, 128)
		offset = 0

		WriteUint32(&tmp, item.ItemID, &offset)
		WriteUint8(&tmp, item.Currency, &offset)
		WriteUint8(&tmp, 1, &offset)            //numopt // x1 / x2 / x3 / x4 / x5 options when purchasing
		WriteUint32(&tmp, item.ItemID, &offset) //optidx
		WriteUint16(&tmp, item.ItemCount, &offset)           //quantity
		WriteUint64(&tmp, 0, &offset)           //continue~day
		WriteUint8(&tmp, 0, &offset)
		WriteUint16(&tmp, item.ItemCount, &offset)
		WriteUint32(&tmp, item.Price, &offset)
		WriteUint32(&tmp, item.Price, &offset)
		WriteUint8(&tmp, 0, &offset) //discount
		WriteUint32(&tmp, 0, &offset)
		WriteUint32(&tmp, 0, &offset)
		WriteUint8(&tmp, item.ItemFlags, &offset) //flags
		WriteUint8(&tmp, 0, &offset)
		WriteUint8(&tmp, 1, &offset)
		WriteUint8(&tmp, 0, &offset)
		WriteUint32(&tmp, item.MileagePWon, &offset) // Milleage Kazan
		WriteUint8(&tmp, item.BlackMarket, &offset) //Black Market
		WriteUint8(&tmp, item.YellowLight, &offset)				//Yellow Light

		optIdx++
		buf = BytesCombine(buf, tmp[:offset])
	}
	ShopReply = buf
}
```

**Comment by IGNRexI** [comment]
@LoveBeforT can you fix the multi option feature for the store? please
x1 / x2 / x3 / x4 / x5
right now when I try 3, the problem occurs and it is wrong


func InitShopReply() {
	buf := make([]byte, 3)
	offset, optIdx := 0, 0
	WriteUint8(&buf, outshoplist, &offset)
	WriteUint16(&buf, uint16(len(ShopItemList)), &offset)
	for _, item := range ShopItemList {
		tmp := make([]byte, 128)
		offset = 0

		WriteUint32(&tmp, item.ItemID, &offset)
		WriteUint8(&tmp, item.Currency, &offset)
		WriteUint8(&tmp, 1, &offset)            //numopt // x1 / x2 / x3 / x4 / x5 options when purchasing
		WriteUint32(&tmp, item.ItemID, &offset) //optidx
		WriteUint16(&tmp, item.ItemCount, &offset)           //quantity
		WriteUint64(&tmp, 0, &offset)           //continue~day
		WriteUint8(&tmp, 0, &offset)
		WriteUint16(&tmp, item.ItemCount, &offset)
		WriteUint32(&tmp, item.Price, &offset)
		WriteUint32(&tmp, item.Price, &offset)
		WriteUint8(&tmp, 0, &offset) //discount
		WriteUint32(&tmp, 0, &offset)
		WriteUint32(&tmp, 0, &offset)
		WriteUint8(&tmp, item.ItemFlags, &offset) //flags
		WriteUint8(&tmp, 0, &offset)
		WriteUint8(&tmp, 1, &offset)
		WriteUint8(&tmp, 0, &offset)
		WriteUint32(&tmp, item.MileagePWon, &offset) // Milleage Kazan
		WriteUint8(&tmp, item.BlackMarket, &offset) //Black Market
		WriteUint8(&tmp, item.YellowLight, &offset)				//Yellow Light

		optIdx++
		buf = BytesCombine(buf, tmp[:offset])
	}
	ShopReply = buf
}

**Comment by LoveBeforT** [comment]
numopt represents the count of item options, you should write 3 option's data into the packet if you set the numopt to 3.
`WriteUint32(&tmp, item.ItemID, &offset)
	WriteUint8(&tmp, item.Currency, &offset)
	numopt := 3
	WriteUint8(&tmp, numopt, &offset)
	for i := 0; i < numopt; i++ {
		WriteUint32(&tmp, item.Optidx, &offset) // the index of Option
		WriteUint16(&tmp, item.ItemCount, &offset)
		WriteUint64(&tmp, 0, &offset)
		WriteUint8(&tmp, 0, &offset) // Refundable
		WriteUint16(&tmp, item.ItemCount, &offset)
		WriteUint32(&tmp, item.Price, &offset)
		WriteUint32(&tmp, item.Price, &offset)
		WriteUint8(&tmp, 0, &offset)
		WriteUint32(&tmp, 0, &offset)
		WriteUint32(&tmp, 0, &offset)
		WriteUint8(&tmp, item.ItemFlags, &offset)
		WriteUint8(&tmp, 0, &offset)
		WriteUint8(&tmp, 1, &offset)
		WriteUint8(&tmp, 0, &offset)
		WriteUint32(&tmp, item.MileagePWon, &offset)
		WriteUint8(&tmp, item.BlackMarket, &offset)
		WriteUint8(&tmp, item.YellowLight, &offset)
	}`

**Comment by LoveBeforT** [comment]
and i don't wanna to talk anymore about CSO2, i have already given up it

**Comment by IGNRexI** [comment]
invalid operation: i < numopt (mismatched types int and uint8) -.-

**Comment by IGNRexI** [comment]
Can you share v8.0 please? @LoveBeforT ?

**Comment by IGNRexI** [comment]
Can you share cso2 server v8.0 code please? @LoveBeforT  ?

**Comment by IGNRexI** [comment]
not working @LoveBeforT  it only pulls the first one

**Comment by IGNRexI** [comment]
you don't want to mess with cso2 yes, I respect that. but i have to ask you to post new v8 codes. If you share v8, I will end all my questions with cso2 anyway.
I want a short term support from you...

My problem with the shop still continues...
I adapted it as you said, but the problem is that it fills the 3 options set with the same data. and (tmp := make([]byte, 128* numopt)) and  where will numopt pull from here?
(x10) it only pulls the first written packet
(x10) it only pulls the first written packet
(x10) it only pulls the first written packet

```css
func InitShopReply() {
	buf := make([]byte, 3)
	offset, optIdx := 0, 0
	WriteUint8(&buf, outshoplist, &offset)
	WriteUint16(&buf, uint16(len(ShopItemList)), &offset)
	for _, item := range ShopItemList {
		tmp := make([]byte, 128* 3)
		offset = 0
		WriteUint32(&tmp, item.ItemID, &offset)
		WriteUint8(&tmp, item.Currency, &offset)
		numopt := 3
		WriteUint8(&tmp, uint8(numopt), &offset)
		for i := 0; i < numopt; i++ {
			fmt.Println(i)
			WriteUint32(&tmp, item.ItemID, &offset) // the index of Option // 
			WriteUint16(&tmp, item.ItemCount, &offset)
			WriteUint64(&tmp, 0, &offset)
			WriteUint8(&tmp, 0, &offset) // Refundable
			WriteUint16(&tmp, item.ItemCount, &offset)
			WriteUint32(&tmp, item.Price, &offset)
			WriteUint32(&tmp, item.Price, &offset)
			WriteUint8(&tmp, 0, &offset)
			WriteUint32(&tmp, 0, &offset)
			WriteUint32(&tmp, 0, &offset)
			WriteUint8(&tmp, item.ItemFlags, &offset) //flags
			WriteUint8(&tmp, 0, &offset)
			WriteUint8(&tmp, 1, &offset)
			WriteUint8(&tmp, 0, &offset)
			WriteUint32(&tmp, item.MileagePWon, &offset)
			WriteUint8(&tmp, item.BlackMarket, &offset)
			WriteUint8(&tmp, item.YellowLight, &offset)
		}
		optIdx++
		buf = BytesCombine(buf, tmp[:offset])
	}
	ShopReply = buf
}
```
